//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkzamenSmolentsev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovari
    {
        public int Kod_Tovara { get; set; }
        public string Articul { get; set; }
        public string Nazvanie { get; set; }
        public string Edenicha_Izmereniy { get; set; }
        public decimal Stoimosty { get; set; }
        public decimal Max_Skidka { get; set; }
        public string Proizvoditel { get; set; }
        public string Postavhik { get; set; }
        public int Kategorii { get; set; }
        public decimal Deystv_Skidka { get; set; }
        public decimal Kolichestvo_Na_Sklade { get; set; }
        public string Opisanie { get; set; }
        public string Izobrazhenie { get; set; }
    
        public virtual Kategorii Kategorii1 { get; set; }
    }
}
